### ISSUE TITLE
compile desktop-app to windows

### ISSUE THREAD

**Issue by Sevauk** [Sevauk/storeit#157]

**Comment by kirly-af** [comment]
?

**Comment by Sevauk** [comment]
I think it's far from working currently

**Comment by kirly-af** [comment]
Well, I've been careful making crossplatform scripts. The only one that will fail is `ipfs:init` (see [here](https://github.com/Sevauk/storeit/blob/master/desktop-app/package.json#L10)) because of the use of the `||` operator which does not exist on Windows. However so far I didn't find a clean way to fix this.

**Comment by Sevauk** [comment]
Alright then but I think it's been a very long time anybody tried to build it on windows.

**Comment by kirly-af** [comment]
We actually have an issue with npm. See [npm/npm#14294](https://github.com/npm/npm/issues/14294).
I don't think we can do something about that.

Though, this is not a big issue as our [preinstall](https://github.com/Sevauk/storeit/blob/master/desktop-app/package.json#L6) could just call a plain JS script instead.
